<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.AspNetCore.Components.WebAssembly">
      <HintPath>..\..\..\..\..\nuget\microsoft.aspnetcore.components.webassembly\8.0.11\lib\net8.0\Microsoft.AspNetCore.Components.WebAssembly.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
