<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Output\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CodeDom" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <None Update="RuntimeGenerators\InsertPeople.tt">
      <LastGenOutput>InsertPeople.cs</LastGenOutput>
      <Generator>TextTemplatingFilePreprocessor</Generator>
    </None>
    <None Update="SqlGenerators\CreateTable.sql">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CreateTable.tt</DependentUpon>
    </None>
    <None Update="SqlGenerators\CreateTable.tt">
      <LastGenOutput>CreateTable.sql</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
    <None Update="SqlGenerators\SqlGenerator_InsertTaxCalendar.sql">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SqlGenerator_InsertTaxCalendar.tt</DependentUpon>
    </None>
    <None Update="SqlGenerators\SqlGenerator_InsertTaxCalendar.tt">
      <LastGenOutput>SqlGenerator_InsertTaxCalendar.sql</LastGenOutput>
      <Generator>TextTemplatingFileGenerator</Generator>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="RuntimeGenerators\InsertPeople.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>InsertPeople.tt</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
